version: 2

jobs:
  build:
    docker:
      - image: novopl/python36:ci-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps-rev1-{{ checksum "setup.py" }}

      - run:
          name: Setup
          command: |
            which pip
            which python
            pip install .
            pip install -r ops/devrequirements.txt
            peltak --help

      - run:
          name: Lint
          command: peltak lint

      - restore_cache:
          key: tox-rev1-{{ checksum "setup.py" }}-{{ checksum "ops/devrequirements.txt" }}

      - run:
          name: Test
          command: tox

      - save_cache:
          key: tox-rev1-{{ checksum "setup.py" }}-{{ checksum "ops/devrequirements.txt" }}
          paths:
          - .tox

      - save_cache:
          key: deps-rev1-{{ checksum "setup.py" }}
          paths:
          - /usr/local/bin
          - /usr/local/lib/python3.6/site-packages
      - store_test_results:
          path: .build
      - store_artifacts:
          path: .build/coverage/
          destination: coverage

  release:
    docker:
      - image: novopl/python36:ci-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps-rev1-{{ checksum "setup.py" }}

      - run:
          name: Setup
          command: pip install .

      - run:
          name: Upload to pypi
          command: |
            peltak pypi configure
            peltak pypi upload
            rm ~/.pypirc

      - run:
          name: Create release tag
          command: |
            peltak release tag -m "$(peltak changelog)"
            git push origin v$(peltak version --porcelain)


workflows:
  version: 2
  main:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
